package game

import game.entity.*
import game.entity.EntityType.*
import game.system.*
import game.system.event.GameSystemEvent.GameSystemEvent

import game.system.event.GameSystemEvent.GameSystemEvent
import map.Dungeon
import util.LineOfSight
import game.entity.Hitbox.*
import game.quest.*
import game.entity.Growth
import game.system.FarmerAISystem

import scala.annotation.tailrec

case class GameState(
    playerEntityId: String,
    entities: Seq[Entity],
    messages: Seq[String] = Nil,
    worldMap: map.WorldMap,
    dungeonFloor: Int = 1,
    gameMode: GameMode = GameMode.Adventure,
    quests: Map[String, QuestState] = Map.empty
) {

  // Index for O(1) entity lookup by ID
  private lazy val entityIndexMap: Map[String, Int] = {
    val m = Map.newBuilder[String, Int]
    var i = 0
    val len = entities.length
    while (i < len) {
      m += (entities(i).id -> i)
      i += 1
    }
    m.result()
  }

  private lazy val entityIndex: Map[String, Entity] =
    entityIndexMap.map { case (id, idx) => id -> entities(idx) }

  val playerEntity: Entity = entityIndex(playerEntityId)

  def getEntity(entityId: String): Option[Entity] = {
    entityIndex.get(entityId)
  }

  // Phased system execution ordering for explicit lifecycle management
  // This addresses ordering inconsistencies and enables event scoping
  // Updated to include new systems from main branch
  private val phases: Seq[Seq[GameSystem]] = Seq(
    // Phase 1: Input processing and early systems
    Seq(
      CullingSystem, // Marks entities active/inactive
      DeathHandlerSystem,
      DebugSystem,
      StairsSpawnSystem,
      ExperienceSystem,
      EnemyAISystem,
      FarmerAISystem,
      MovementSystem,
      VelocitySystem,
      WaveSystem,
      ItemUseSystem, // New unified item system
      HealingSystem, // Handles healing events
      EquipInputSystem,
      DescendStairsSystem,
      TradeSystem, // Handles buy/sell transactions
      ConversationSystem // Handles conversation actions
    ),
    // Phase 2: Creation and spawning
    Seq(
      MessageSystem, // Handles message events
      SpawnEntitySystem, // Enhanced to handle collision-checked spawning
      SpawnProjectileSystem,
      WorldGenerationSystem,
      WildAnimalSpawnSystem, // Added dynamic animal spawning
      VillageSystem,
      CaravanSystem, // Added caravan logic
      WaitSystem,
      OpenDoorSystem,
      GrowthSystem // Handles crop growth
    ),
    // Phase 3: Combat and collision processing
    // InventorySystem moved here to handle CollisionEvent before it's dropped
    // CollisionEvent events are dropped after this phase
    Seq(
      CollisionCheckSystem,
      AttackSystem,
      RangeCheckSystem,
      CollisionHandlerSystem,
      DamageSystem,
      InventorySystem // Moved from Phase 4 to handle CollisionEvent for pickup
    ),
    // Phase 4: Equipment and progression
    Seq(
      EquipmentSystem,
      InitiativeSystem,
      QuestSystem,
      LevelUpSystem,
      SightMemorySystem,
      EventMemorySystem
    )
  )

  // Maintain backward compatibility by exposing flattened systems
  val systems: Seq[GameSystem] = phases.flatten

  def updateWithSystems(initialEvents: Seq[GameSystemEvent]): GameState = {
    val (_, finalState) = phases.zipWithIndex.foldLeft((initialEvents, this)) {
      case (
            (incomingEvents, stateAtPhaseStart),
            (systemsInPhase, phaseIndex)
          ) =>
        // Execute all systems in this phase, accumulating events generated within the phase
        val (stateAfterPhase, phaseEmittedEvents) = systemsInPhase.foldLeft(
          (stateAtPhaseStart, Vector.empty[GameSystemEvent])
        ) { case ((currentState, accumulatedPhaseEvents), system) =>
          // Each system sees incoming events plus events generated by previous systems in this phase
          val visibleEvents = incomingEvents ++ accumulatedPhaseEvents

          val (newState, newEvents) = system.update(currentState, visibleEvents)

          (newState, accumulatedPhaseEvents ++ newEvents)
        }

        // Combine incoming events with events generated during this phase
        val allPhaseEvents = incomingEvents ++ phaseEmittedEvents

        // Apply event scoping rules based on phase
        val carryOverEvents: Seq[GameSystemEvent] = phaseIndex match {
          case 2 => // After Phase 3 (collision phase): drop CollisionEvent only
            allPhaseEvents.collect {
              case e
                  if !e.isInstanceOf[
                    game.system.event.GameSystemEvent.CollisionEvent
                  ] =>
                e
            }
          case _ => // All other phases: carry over all events (including InputEvent)
            allPhaseEvents
        }

        (carryOverEvents, stateAfterPhase)
    }
    finalState
  }

  def updateEntity(entityId: String, newEntity: Entity): GameState = {
    entityIndexMap.get(entityId) match {
      case Some(index) => copy(entities = entities.updated(index, newEntity))
      case None        => this
    }
  }

  /** Update an entity by ID. Returns unchanged GameState if entity not found.
    * Note: Silent failure is intentional to avoid crashes. Callers should
    * ensure entity exists before calling if failure needs to be detected.
    */
  def updateEntity(entityId: String, update: Entity => Entity): GameState = {
    entityIndexMap.get(entityId) match {
      case Some(index) => copy(entities = entities.updated(index, update(entities(index))))
      case None        => this
    }
  }

  lazy val actorSpatialIndex: Map[Point, Entity] = {
    val builder = Map.newBuilder[Point, Entity]
    entities.foreach { entity =>
      if (entity.has[Movement] && (entity.entityType == EntityType.Enemy || entity.entityType == EntityType.Player)) {
        entity.get[Movement].foreach(m => builder += (m.position -> entity))
      }
    }
    builder.result()
  }

  def getActor(point: Point): Option[Entity] = actorSpatialIndex.get(point)

  def add(entity: Entity): GameState = {
    copy(entities = entities :+ entity)
  }

  def remove(entityId: String): GameState = {
    copy(entities = entities.filterNot(_.id == entityId))
  }

  lazy val lockedDoorPositions: Set[Point] = {
    entities.collect {
      case e if e.entityType.isInstanceOf[LockedDoor] =>
        e.get[Movement].map(_.position)
    }.flatten.toSet
  }

  def getVisiblePointsFor(entity: Entity): Set[Point] = {
    val isBlocked = (p: Point) =>
      worldMap.staticLineOfSightBlockingPoints.contains(
        p
      ) || lockedDoorPositions.contains(p)

    val builder = Set.newBuilder[Point]
    for {
      entityPosition <- entity.hitbox
      lineOfSight = LineOfSight.getVisiblePoints(
        entityPosition,
        isBlocked,
        10
      )
    } builder ++= lineOfSight

    builder.result()
  }

  def addMessage(message: String): GameState = {
    copy(messages = message +: messages)
  }

  def acceptQuest(
      questId: String,
      progressBaseline: Int = 0
  ): GameState = {
    if (!quests.contains(questId)) {
      copy(
        quests = quests + (
          questId -> QuestState(QuestStatus.Active, progressBaseline)
        )
      )
    } else {
      this
    }
  }

  def completeQuest(questId: String): GameState = {
    if (quests.get(questId).exists(_.status == QuestStatus.Active)) {
      copy(
        quests = quests.updatedWith(questId)(
          _.map(_.copy(status = QuestStatus.Completed))
        )
      )
    } else {
      this
    }
  }

  def isQuestActive(questId: String): Boolean =
    quests.get(questId).exists(_.status == QuestStatus.Active)

  def isQuestCompleted(questId: String): Boolean =
    quests.get(questId).exists(_.status == QuestStatus.Completed)

  lazy val lineOfSightBlockingPoints: Set[Point] =
    worldMap.staticLineOfSightBlockingPoints ++ lockedDoorPositions

  lazy val dynamicMovementBlockingPoints: Set[Point] =
    entities
      .filter(entity =>
        entity
          .get[EntityTypeComponent]
          .exists(c =>
            c.entityType == EntityType.Enemy || c.entityType == EntityType.Player || c.entityType
              .isInstanceOf[LockedDoor]
          )
      )
      .flatMap { entity =>
        // Get all points occupied by multi-tile entities (like the boss)
        val basePosition =
          entity.get[Movement].map(_.position).getOrElse(Point(0, 0))
        entity.get[game.entity.Hitbox] match {
          case Some(hitbox) =>
            // Multi-tile entity: include all hitbox points
            hitbox.points.map(hitboxPoint =>
              Point(
                basePosition.x + hitboxPoint.x,
                basePosition.y + hitboxPoint.y
              )
            )
          case None =>
            // Single-tile entity: just the base position
            Set(basePosition)
        }
      }
      .toSet

  lazy val movementBlockingPoints: Set[Point] =
    worldMap.staticMovementBlockingPoints ++ dynamicMovementBlockingPoints

  def isBlocked(points: Set[Point], ignoreEntityId: String = ""): Boolean = {
    if (worldMap.staticMovementBlockingPoints.intersect(points).nonEmpty)
      return true
    entities.exists { entity =>
      entity.id != ignoreEntityId &&
      entity
        .get[EntityTypeComponent]
        .exists(c =>
          c.entityType == EntityType.Enemy ||
            c.entityType == EntityType.Player ||
            c.entityType.isInstanceOf[LockedDoor]
        ) &&
      entity.collidesWith(points)
    }
  }

  lazy val drawableChanges: Seq[Set[(Point, Sprite)]] = {
    import game.entity.Drawable.*
    entities.map(_.sprites)
  }
}
