name: PR Preview Cleanup

on:
  pull_request:
    branches: [ main ]
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Cleanup PR Preview
      run: |
        # Configure git
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if gh-pages branch exists
        if git ls-remote --exit-code --heads origin gh-pages; then
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          
          # Remove PR directory if it exists
          if [ -d "pr-${{ github.event.number }}" ]; then
            rm -rf "pr-${{ github.event.number }}"
            git add .
            git commit -m "Remove PR #${{ github.event.number }} preview" || exit 0
            git push origin gh-pages
            echo "Cleaned up PR #${{ github.event.number }} preview"
          else
            echo "No preview found for PR #${{ github.event.number }}"
          fi
        else
          echo "No gh-pages branch found, nothing to clean up"
        fi

    - name: Comment on PR about cleanup
      uses: actions/github-script@v7
      with:
        script: |
          const prNumber = context.payload.pull_request.number;
          
          const comment = `## 🧹 PR Preview Cleaned Up
          
          The preview for this PR has been automatically removed from GitHub Pages.

          **What was cleaned up:**
          - Removed \`pr-${prNumber}/\` directory from gh-pages branch
          - Preview URL is no longer accessible

          Thank you for your contribution! 🎉`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: prNumber,
            body: comment
          });